	<!-- main start -->
			<div id="main">

<div class="container">
<div id="bottom_container">
    <div id="privPol_title">
        <h1> Terms and Conditions</h1>
    </div>
    <div id="privPol">
        <div id="policy">
                        <div class="wrap-terms">
<h3>TERMS OF ACCESS AND USE</h3>
<p>2015 Qology Direct LLC <sup>TM</sup> . All rights reserved.</p>
<p>PLEASE READ THIS CAREFULLY. THE FOLLOWING TERMS AND CONDITIONS CONSTITUTE A BINDING AGREEMENT BETWEEN YOU AND QOLOGY DIRECT LLC™ (“Company”). By accessing, browsing and/or otherwise using this web site (“Site”), you acknowledge that you have read, understood and agreed to be bound by these terms and conditions, and to comply with all applicable laws and regulations, including U.S. export and re-export control laws and regulations. If you do not agree to all of these terms and conditions, do not access, browse and/or use this Site. The material provided on this Site is protected by law, including, but not limited to, United States copyright law and international treaties.</p>
<p>These terms apply to your access to and use of this Site and do not alter in any way the terms and conditions of any other agreement you may have with Company for products, services or otherwise, unless otherwise directed by Company. If you breach any of these terms and conditions, your authorization to use this Site automatically terminates and you must immediately destroy any downloaded or printed materials and discontinue use of any hyperlinks to this Site. A breach of this Agreement may subject you to civil and criminal liability, including monetary damages.</p>
<p><strong>OPERATOR</strong><br />
The Site is operated by Qology Direct LLC ™, a company incorporated under the laws of Florida whose principal business address is 5297 West Copans Road, Margate, FL 33063. Company makes no representation that the Site, or Content available through it, are appropriate or available for use at other locations outside the United States, and access to the Site from territories where the Site or Content are illegal or prohibited. If you access the Site from a location outside the United States, you are responsible for compliance with all local laws.
</p>
<p><strong>REVISIONS TO THIS AGREEMENT</strong><br />
Company reserves the right to change this Agreement from time to time and any modification to this Agreement will be effective upon posting to the Site. Your continued use of the Site after the posting of a modification to this Agreement constitutes your acceptance of the modification. Your use of the Site will be subject at all times to the most current version of this Agreement.</p>
<p><strong>USE RESTRICTIONS</strong><br />
Intellectual Property Rights. All images, audio, video and related informational materials in any medium and the selection and arrangement thereof, including related text, captions, or information (collectively referred to as “Content”), is owned by Company or our licensors and is protected by US and international copyright laws, trade dress, moral rights, and other intellectual property rights. Except as explicitly permitted under this Agreement, no portion or element of this Site or its Content may be copied or retransmitted via any means and all related rights shall remain the exclusive property of Company and its licensors. You may not copy, modify, translate, publish, perform, broadcast, transmit, download, distribute, display, prepare derivative works of, sell or otherwise exploit any Content appearing on or through the Site for any purpose without our prior written consent and that of our licensors or suppliers if required. You may not “mirror” any material contained on this Site on any other server without prior written permission from Company. Any unauthorized use of any material contained on this Site may violate copyright laws, trademark laws, the laws of privacy and publicity and communications regulations and statutes and could subject you to civil and criminal penalties.</p>
<p>FOR THE PROTECTION OF COMPANY AND ITS LICENSORS, CONTENT MAY BE VISIBLY, INVISIBLY, OR ELECTRONICALLY WATERMARKED AND MAY INCLUDE THE USE OF DIGITAL RIGHTS MANAGEMENT SYSTEM TECHNOLOGY WITHIN CONTENT. SUCH TECHNOLOGY MAY PERMIT ONLINE CRAWLING OR TRACKING OF CONTENT OBTAINED FROM COMPANY AND/OR OTHER METHODS OF PROTECTING, MONITORING, OR TRACKING THE UNAUTHORIZED USE OF THE CONTENT (“RIGHTS MANAGEMENT SYSTEMS (RMS))”. If you do not consent to Company’s use of RMS, do not use the Site or any Content. You shall not knowingly disable any such technology or tool. You may not remove any copyright or other proprietary notices contained in the Content, caption information, or any other material on this Site.</p>
<p>Trademarks. Qology Direct is a trademark or registered trademark of Company. All other trademarks are the property of their respective owners. You are not permitted to use any trademark displayed on this Site without the prior written consent of Company or the owner of such trademark.</p>
<p>Hyperlinks. You are granted a limited, nonexclusive right to create a “hypertext” link to this Site provided that such link is to the entry page of this Site and does not portray Company or any of the products or services featured on the Site in a false, misleading, derogatory, or otherwise defamatory manner. This limited right may be revoked at any time for any reason whatsoever. You may not use framing techniques to enclose any Company trademark, logo or trade name or other proprietary information including the images found at the Site, the content of any text or the layout/design of any page or any form contained on a page without Company’s express written consent. Links to third party sites on this Site are provided solely as convenience to you. If you use these links, you will leave this Site. Company has not reviewed all of these third party sites and does not control and is not responsible for any of these sites, their content or their policies, including, without limitation, privacy policies or lack thereof. Company does not endorse or make any representations about third party sites or any information, software or other products or materials found there, or any results that may be obtained from using them. If you decide to access any of the third party sites linked to this site, you do so entirely at your own risk. You acknowledge and agree that Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by, or in connection with the use of or reliance on any such third party sites.</p>
<p>Downloadable Content. Any Content that is made available to download from this Site is the copyrighted work of Company and/or its suppliers and affiliates and subject to the Use Restrictions stated herein.</p>
<p>Limited Access. Except as otherwise expressly permitted by Company, any access or attempt to access other areas of the Company computer system or other information contained on the system for any purposes is strictly prohibited. You agree that you will not use any robot, spider, other automatic device, or manual process to “screen scrape,” monitor, “mine,” or copy the Web pages on the Site or the content contained therein without Company’s prior, express, and written permission. You will not spam or send unsolicited e-mail to any other user of the Site for any reason. You agree that you will not use any device, software or routine to interfere or attempt to interfere with the proper working of the Site. You agree that you will not take any action that imposes an unreasonable or disproportionately large load on Company’s infrastructure.</p>
<p>Acceptable Use Policy. While using the Site, you agree to comply with all applicable laws, rules and regulations and agree not to engage in unacceptable use of the Site. You shall not post, transmit, e-mail, re-transmit or store material on or through any of the services provided by Company (the “Services”) which, in the sole judgment of the Company: (i) is in violation of any local, state, federal or non-United States law or regulation, (ii) is threatening, obscene, indecent, defamatory or that otherwise could adversely affect any individual, group or entity (collectively, “Persons”) or (iii) violates the rights of any person, including rights protected by copyright, trade secret, patent or other intellectual property or similar laws or regulations. You shall be responsible for determining what laws or regulations are applicable to your use of the Services. In addition, you may only use the Services in a manner that, in the Company’s sole judgment, is consistent with the purposes of such Services. If you are unsure of whether any contemplated use or action is permitted, please contact the Company at webmaster@qologydirect.com. By way of example, and not limitation, the following uses described below of the Services are expressly prohibited:</p>
<ul>
<li>upload, post, e-mail or otherwise transmit any information, data, text, software, music, sound, photographs, graphics, video, messages or other materials (collectively, “Content”) that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive of another’s privacy, hateful, or racially, ethnically or otherwise objectionable. Pornography and pornographic related merchandising are prohibited under all Services, including providing links to pornographic content elsewhere;</li>
<li>harm minors in any way;</li>
<li>impersonate any person or entity, including, but not limited to, a Company official, forum leader, guide or host, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
<li>forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Services or develop restricted or password-only access pages, or hidden pages or images (those not linked to from another accessible page);</li>
<li>upload, post, e-mail or otherwise transmit any Content that you do not have a right to transmit under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</li>
<li>upload, post, e-mail or otherwise transmit any Content that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party;</li>
<li>upload, post, e-mail or otherwise transmit any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
<li>disrupt the normal flow of dialogue, cause a screen to “scroll” faster than other users of the Services are able to type, or otherwise act in a manner that negatively affects other users’ ability to engage in real time exchanges;</li>
<li>restrict or inhibit other users from visiting the Site, including without limitation, by means of “hacking or defacing any portion of the Site;</li>
<li>collect, harvest, mine or obtain by any other manner information about others, including but not limited to, phone numbers, email addresses, and other personal information;</li>
<li>“stalk” or otherwise harass another;</li>
<li>promote or provide instructional information about illegal activities, promote physical harm or injury against any group or individual, or promote any act of cruelty to animals. This may include, but is not limited to, providing instructions on how to assemble bombs, grenades and other weapons, and creating “Crush” sites; and</li>
<li>effect security breaches or disruptions of Internet communication. Security breaches include, but are not limited to, accessing data of which you are not an intended recipient or logging into a server or account that you are not expressly authorized to access.</li>
</ul>
<p>You further agree not to (i) interfere with or disrupt any other user’s quiet enjoyment of the Site; or (ii) interfere with or disrupt or attempt to interfere with or disrupt the security of the Site or otherwise cause harm to the Site. </p>
<p><strong>DISCLAIMER OF WARRANTIES</strong><br />
This Site, including all software, functions, Content, and information, is provided “as is” without warranties of any kind, either express or implied. Company disclaims all warranties, express or implied, including, but not limited to, warranties of quiet enjoyment and non-infringement and implied warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, title, quiet enjoyment, system integration, and informational content. Company does not warrant or make any representations regarding the operation of this Site, the use, validity, accuracy or reliability of, or the results of the use of the Content on this Site or any other sites linked to this Site. The Content may be out of date, and Company makes no commitment to update the Content. Company does not and cannot guarantee or warrant that the files available for downloading from this Site, if any, will be free from infection, viruses, worms, Trojan horses, or other code that manifest contaminating or destructive properties. Company does not warrant that this Site, software, Content, products, or services will be uninterrupted or error-free or that any defects in this Site, software, Content, products, or services will be corrected.</p>
<p><strong>LIMITATION OF LIABILITY</strong><br />
In no event will Company, its licensors or other third parties mentioned at or in this Site be liable for any damages, including, without limitation direct, indirect, special, incidental, or consequential damages, damages resulting from lost profits, lost data or business interruption arising out of or relating to the use, inability to use, or resulting from the use of this Site, any Web sites linked to this Site, the content, software or other information contained in any or all such sites, products related to or ordered via this Site, whether based on warranty, contracts, statutes, regulations, tort (including but not limited to, negligence) or any other legal theory and whether or not advised of the possibility of such damages. If your use of the Content or information from this Site results in the need for servicing, repair or correction of equipment or data, you assume all costs thereof. Some states do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.</p>
<p><strong>U.S. GOVERNMENT RESTRICTED RIGHTS</strong><br />
The Content on this Site is provided with “RESTRICTED RIGHTS.” Use, duplication, or disclosure by the government is subject to restrictions as set forth in applicable laws and regulations. Use of the Content by the government constitutes acknowledgment of Company’s proprietary rights in them.</p>
<p><strong>COPYRIGHT INFRINGEMENT POLICY</strong><br />
In accordance with the requirements set forth in the Digital Millennium Copyright Act, Title 17 United States Code Section 512(c)(2) (“DMCA”), Qology Direct LLC ™ will investigate notices of copyright infringement and take appropriate remedial action. If you believe that any Content on the Site has been used or copied in a manner that infringes your work, please provide a written notification of claimed copyright infringement to the Designated Agent for the Site containing the following elements as set forth in the DMCA:</p>
<ul>
<li>a physical or electronic signature of the owner of the copyright interest that is alleged to have been infringed or the person authorized to act on behalf of the owner;</li>
<li>identification of the copyrighted work(s)claimed to have been infringed, including copyright date;</li>
<li>identification of the Content that you claim to be infringing and which you request be removed from the Site or access to which is to be disabled along with a description of where the infringing Content is located;</li>
<li>information reasonably sufficient to allow us to contact you, such as a physical address, telephone number and an email address;</li>
<li>a statement by you that you have a good faith belief that the use of the Content identified in your written notification in the manner complained of is not authorized by you or the copyright owner, its agent or the law; and</li>
<li>a statement by you that the information in your written notification is accurate and that, under penalty of perjury, you are the copyright owner or authorized to act on behalf of the copyright owner.</li>
</ul>
<p>Company’s designated agent for the written notification of claims of copyright infringement can be contacted at the following address:</p>
<p>Designated Agent – Copyright Infringement Claims<br />
Qology Direct LLC ™<br />
Attn: Legal Department<br />
5297 West Copans Road<br />
Margate, FL 33063<br />
Email: legal@qologydirect.com</p>
<p/>
<p><strong>YOUR INFORMATION</strong><br />
While Company may provide you with an opportunity to provide comments or ask questions regarding the Content posted on the Site, we do not want nor do we solicit confidential or proprietary information from you. Any unsolicited information you provide, including but not limited to feedback, suggestions, data, or plans or ideas for products or services, shall be deemed non-proprietary and non-confidential and Company shall have no obligation to protect such information from further disclosure or distribution. By providing us with such information, you are granting us an unrestricted and irrevocable right to reproduce, use, publish, broadcast, disclose, display, perform, modify, transmit, distribute or otherwise use and exploit the information without restriction and without compensation.</p>
<p><strong>INDEMNIFICATION</strong><br />
You agree to indemnify, defend and hold Company, its licensors and affiliates and their respective assigns, harmless from any loss, liability, damages or claim, including reasonable attorneys’ fees and costs, that arise directly or indirectly from (i) your activities in connection with the Site, (ii) a breach of this Agreement, including, but not limited to, any violation of the acceptable use policy, or (iii) any allegation that any information that you provide via the Site infringes or otherwise violates the copyright, trademark, trade secret or other intellectual property, privacy or other rights of any third party. You also agree to reimburse on demand any and all indemnified parties for any losses incurred by such indemnified parties to which this indemnification provision relates.</p>
<p><strong>AVAILABILITY</strong><br />
Company makes reasonable efforts to ensure that the Site is available 24 hours a day 7 days a week. You agree that from time to time the Site or portions thereof may be inoperable or inaccessible for any reason, including, without limitation, (i) equipment malfunctions; (ii) periodic maintenance procedures or repairs which Company may undertake from time to time; or (iii) causes beyond the control of Company or which are not reasonably foreseeable by Company. Some Content on the Site may have been created in file formats which are not error-free and Company does not guarantee that the Site will not be affected by such errors. You are responsible for all costs and charges that you may incur in order to access and use the Site and the Content.</p>
<p><strong>APPLICABLE LAWS &amp; MISCELLANEOUS</strong><br />
If any provision(s) of this Agreement is held by a court of competent jurisdiction to be contrary to law, then such provision(s) shall be construed, as nearly as possible, to reflect the intentions of the parties with the other provisions remaining in full force and effect. Company’s failure to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision unless acknowledged and agreed to by Company in writing. The section titles in this Agreement are solely used for the convenience of the parties and have no legal or contractual significance. This Agreement may be assigned in whole or in part by Company. This Agreement shall be governed by and construed in accordance with the laws of the State of Florida without regard to conflict of law provisions. You irrevocably and unconditionally consent to submit all disputes arising under this Agreement to arbitration in Fort Lauderdale, Florida, before a sole impartial arbitrator. The arbitration shall be administered by the AAA pursuant to its Commercial Rules and the arbitrator shall be selected pursuant to the rules and procedures of the AAA. The decision of the arbitrator shall be final and non-appealable. Judgment on the award may be entered in any court having competent jurisdiction.</p>
<p><strong>Last Updated:</strong> January 1, 2015</p>
</div>
                        </div>
        <div class="clear"></div>
    </div>
    <div class="clear">
    </div>
</div>
</div>
	</div>
	<!-- End inner-wrapper -->

	<div style="clear:both;"></div>

		<!-- </div> -->

		<!-- main end -->
